.

diff --git a/Jenkins_docker_dotnet_QA b/Jenkins_docker_dotnet_QA
--- a/Jenkins_docker_dotnet_QA
+++ b/Jenkins_docker_dotnet_QA
@@ -36,8 +36,10 @@ pipeline{
                     label AGENTS_LIST
                 }
             }
+            steps{
+                git branch: env.gitlabBranch, url: env.gitlabUrl + "/" + env.gitlabGroup + "/" + env.gitlabPproject + ".git"
 
-            git branch: env.gitlabBranch, url: env.gitlabUrl + "/" + env.gitlabGroup + "/" + env.gitlabPproject + ".git"
+            }
 
             // steps {
             //     echo "starting SCM checkout"
@@ -82,93 +84,95 @@ pipeline{
                     label AGENTS_LIST
                 }
             }
+            steps{
 
-            def QA_WD = pwd()
+                def QA_WD = pwd()
 
-            script {
-                echo "starting QA"
-                withSonarQubeEnv('SonarQubeNumera') {
-                    script {
-                        
-                        def SONAR_URL = env.SONAR_HOST_URL
-                        def scannerHome = tool 'sonarQubeScanner4'
-                        def javaHome = tool 'JDK_21.0.3'
-                        if (env.SONAR_IS_UP == 'true') {
+                script {
+                    echo "starting QA"
+                    withSonarQubeEnv('SonarQubeNumera') {
+                        script {
+                            
+                            def SONAR_URL = env.SONAR_HOST_URL
+                            def scannerHome = tool 'sonarQubeScanner4'
+                            def javaHome = tool 'JDK_21.0.3'
+                            if (env.SONAR_IS_UP == 'true') {
 
-                            echo "=== Verifica SonarScanner for .NET ==="
-                            sh "dotnet sonarscanner --version || echo 'SonarScanner non disponibile - verificare installazione'"
+                                echo "=== Verifica SonarScanner for .NET ==="
+                                sh "dotnet sonarscanner --version || echo 'SonarScanner non disponibile - verificare installazione'"
 
-                            sh "dotnet sonarscanner begin -k:'${gitlabPproject}-${branch}' -d:sonar.host.url='${SONAR_URL}' -d:sonar.projectVersion='${APPLICATION_VERSION}' -d:sonar.cs.dotnet.solution='${projectFile}'"
+                                sh "dotnet sonarscanner begin -k:'${gitlabPproject}-${branch}' -d:sonar.host.url='${SONAR_URL}' -d:sonar.projectVersion='${APPLICATION_VERSION}' -d:sonar.cs.dotnet.solution='${projectFile}'"
 
-                            sh "dotnet build '${projectFile}'"
+                                sh "dotnet build '${projectFile}'"
 
-                            sh "dotnet sonarscanner end"
+                                sh "dotnet sonarscanner end"
+                                        
+                                // -d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
+                                // -d:sonar.coverage.exclusions="**Test*.cs"
                                     
-                            // -d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
-                            // -d:sonar.coverage.exclusions="**Test*.cs"
-                                
+                            }
                         }
                     }
                 }
-            }
 
-            def SONAR_URL = env.SONAR_HOST_URL
+                def SONAR_URL = env.SONAR_HOST_URL
 
-            script{
-                sleep(30) 
-                timeout(time: 360, unit: 'SECONDS') {
-                    if (env.SONAR_IS_UP == 'true') {
-                        def qg = waitForQualityGate() 
-                        // def branch = env.gitlabBranch
-                        // branch = branch.replace('/', '-')
-                        // branch = branch.replace('*', '')
-                        
-                        withCredentials([usernameColonPassword(credentialsId: 'sonarqube-api-token', variable: 'USERPASS')]) {
-                            //sh "curl -X POST -u $USERPASS -i '" + SONAR_URL + "/api/permissions/apply_template?templateName=Template-Sonarqube_" + gitlabGroup + "&projectKey=" + gitlabPproject + "-" + branch + "'"
-                            sh "curl -X POST -u $USERPASS -i '" + SONAR_URL + "/api/permissions/apply_template?templateName=Default%20template&projectKey=" + gitlabPproject + "-" + branch + "'"
-                            echo 'Configurato permission template per il project sonar'
+                script{
+                    sleep(30) 
+                    timeout(time: 360, unit: 'SECONDS') {
+                        if (env.SONAR_IS_UP == 'true') {
+                            def qg = waitForQualityGate() 
+                            // def branch = env.gitlabBranch
+                            // branch = branch.replace('/', '-')
+                            // branch = branch.replace('*', '')
+                            
+                            withCredentials([usernameColonPassword(credentialsId: 'sonarqube-api-token', variable: 'USERPASS')]) {
+                                //sh "curl -X POST -u $USERPASS -i '" + SONAR_URL + "/api/permissions/apply_template?templateName=Template-Sonarqube_" + gitlabGroup + "&projectKey=" + gitlabPproject + "-" + branch + "'"
+                                sh "curl -X POST -u $USERPASS -i '" + SONAR_URL + "/api/permissions/apply_template?templateName=Default%20template&projectKey=" + gitlabPproject + "-" + branch + "'"
+                                echo 'Configurato permission template per il project sonar'
 
 
-                            //estrazione coverage da sonar
-                            sh "curl --fail -s -L -X GET -u $USERPASS '$SONAR_URL/api/measures/component?component=${gitlabPproject}-${branch}&metricKeys=coverage,sqale_debt_ratio' -o sonar_measures.json"
-                            def coverageFile = readFile "sonar_measures.json"
-                            def coverageJson = new JsonSlurper().parseText(coverageFile)
-                            Float coverage = 0
-                            Float techDeb = 0
-                            Float securityRating = 0
+                                //estrazione coverage da sonar
+                                sh "curl --fail -s -L -X GET -u $USERPASS '$SONAR_URL/api/measures/component?component=${gitlabPproject}-${branch}&metricKeys=coverage,sqale_debt_ratio' -o sonar_measures.json"
+                                def coverageFile = readFile "sonar_measures.json"
+                                def coverageJson = new JsonSlurper().parseText(coverageFile)
+                                Float coverage = 0
+                                Float techDeb = 0
+                                Float securityRating = 0
 
-                            coverageJson.component.measures.each {
-                                if (it.metric == "coverage" && it.value) coverage = it.value.toFloat()
-                                if (it.metric == "sqale_debt_ratio" && it.value) techDeb = it.value.toFloat()
-                                if (it.metric == "security_rating" && it.value) securityRating = it.value.toFloat()
+                                coverageJson.component.measures.each {
+                                    if (it.metric == "coverage" && it.value) coverage = it.value.toFloat()
+                                    if (it.metric == "sqale_debt_ratio" && it.value) techDeb = it.value.toFloat()
+                                    if (it.metric == "security_rating" && it.value) securityRating = it.value.toFloat()
+                                }
+
+                                //aggiungo l'url della dashboard sonar alla mappa
+                                QA_RESULT.put("sonarqube.report-url", "$SONAR_URL/dashboard?id=" + gitlabPproject + "-" + branch)
+                                //aggiungo l'esito dell'analisi Sonar
+                                //rendo sonarQUBE non bloccante, il primo KO diventa OK
+                                QA_RESULT.put("sonarqube.esito", env.SONAR_IS_BLOCKING != 'false' && qg.status != 'OK' && qg.status != 'WARN' ? "KO" : "OK")
+                                //aggiungo la descrizione per sonar
+                                QA_RESULT.put("sonarqube.description", "Coverage del progetto: " + coverage + "\ndebito tecnico: " + techDeb + "\nsecurity rating: " + securityRating)
                             }
 
-                            //aggiungo l'url della dashboard sonar alla mappa
-                            QA_RESULT.put("sonarqube.report-url", "$SONAR_URL/dashboard?id=" + gitlabPproject + "-" + branch)
-                            //aggiungo l'esito dell'analisi Sonar
-                            //rendo sonarQUBE non bloccante, il primo KO diventa OK
-                            QA_RESULT.put("sonarqube.esito", env.SONAR_IS_BLOCKING != 'false' && qg.status != 'OK' && qg.status != 'WARN' ? "KO" : "OK")
-                            //aggiungo la descrizione per sonar
-                            QA_RESULT.put("sonarqube.description", "Coverage del progetto: " + coverage + "\ndebito tecnico: " + techDeb + "\nsecurity rating: " + securityRating)
+                            if (qg.status != 'OK' && qg.status != 'WARN') {
+                                echo("Pipeline in errore a causa del Quality Gate impostato su Sonar. Status: ${qg.status}. Controllare la link $SONAR_URL/dashboard?id=" + gitlabPproject + "-" + branch)
+                                echo(QA_RESULT["sonarqube.description"])
+                                currentBuild.result = 'UNSTABLE'
+                            }
+                        } else {
+                            echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
+                            echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
+                            echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
+                            echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
+
+                            echo 'ATTENZIONE VERIFICA QUALITY GATE SONAR NON ATTIVO Variabile ambiente env.SONAR_IS_UP ' + env.SONAR_IS_UP
+
+                            echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
+                            echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
+                            echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
+                            echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
                         }
-
-                        if (qg.status != 'OK' && qg.status != 'WARN') {
-                            echo("Pipeline in errore a causa del Quality Gate impostato su Sonar. Status: ${qg.status}. Controllare la link $SONAR_URL/dashboard?id=" + gitlabPproject + "-" + branch)
-                            echo(QA_RESULT["sonarqube.description"])
-                            currentBuild.result = 'UNSTABLE'
-                        }
-                    } else {
-                        echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-                        echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-                        echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-                        echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-
-                        echo 'ATTENZIONE VERIFICA QUALITY GATE SONAR NON ATTIVO Variabile ambiente env.SONAR_IS_UP ' + env.SONAR_IS_UP
-
-                        echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-                        echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-                        echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
-                        echo 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
                     }
                 }
             }
